### ISSUE TITLE
multihash name on npm

### ISSUE THREAD

**Issue by daviddias** [jaredhanson/node-multihash#1]
Hi @jaredhanson! 

Would you be available of releasing the multihash name on `npm`? We've developed a `multihash` format that is used across the entire [IPFS project](https://ipfs.io/) and some of our users and developers have been confused often by the fact that the `multihash` module on npm is not actually the one they should download, instead, they should installed [`multihashes`](https://github.com/jbenet/js-multihash) (which was the closest name we could get). 

I'm also requesting this because I noticed that this module doesn't have any activity for quite a while.

Hope that this is ok with you. Thank you for understanding :)

**Comment by jaredhanson** [comment]
This module doesn't have any activity because its implementation is complete (100% test coverage and no bugs).

This module implements a multi-valued hash (a multi-hash), so the name it is published it under is relevant and not in violation of a trademark or other valid rationale for releasing the existing name.  So I think its best to leave it as its original name, and avoid breaking dependencies of the package itself.

It is unfortunate that the single-level npm namespace causes naming collisions and discovery issues, but I'm confident that the community can address those issues going forward.  One option that is appearing more and more is the use of scoped packages.  Releasing under `@multiformats/multihash` would be an option, and if the other multiformat packages followed suit, it might help establish a convention that makes it easy for users and developers working with IPFS.

IPFS is excellent work by the way, so thank you for that!
